# Generated by Django 6.0.2 on 2026-02-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_commande_adresse_livraison_commande_date_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
